import os
import subprocess
import tkinter as tk
from tkinter import filedialog
import numpy as np

import customtkinter
import CTkMenuBar
import matplotlib
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg

import ParticulateObjectFrame
import ScrollableObjectFrame
import SoluteObjectFrame
import SimulationFrame
import GeometryFrame
import ReactionFrame

import SaveFileBuilder
import FileLoader
import FileController
import PlotWindow

#TODO:
'''
 For 1.0 release:
kinetics are not loaded from file
    load mu max from file
    idea 1:
    save a number to save file with indicates which kind of dependance is used
    there could be a number which indicates a custom equation
    idea 2: parse 'mu' and find the dependancies by hand
A similar problem occurs for Sin

Build a distributable package 

 After 1.0 release:
when you load up a new file, should it have a simple base case in it?
clean up file menu - make it scale
Displaying the plots generated by Biofilm.jl in an interactive way, add entry box which shows time, allows for entry
Loading a saved profile of parameters - still need to put loaded params into entry boxes
Support for user defined interactions between particulates/solutes
csv file
Address performance issues - especially when resizing
Implement tool tips and units for all parameters
Equation viewer/editor 
Test distributable across operating systems and screens
'''

#BUGS: 
'''
 To be fixed before next release:
Deleted particulates still show up in reactions menu kinetics section
must open reactions menu before using 'save as' button
deleting multiple objects results in pop index out of range, maybe after a delete, update all objects' indices
scrolling on soluteSOF not working?

 Lower priority:
opening reactions menu with no particulates defined gives 'list index out of range' from SaveFileBuilder.py, line 142


BUGS NOTES
working on the bugs related to deleting solutes/particulates. The bug seems to actually be with the CTk grid system. To recreate this
bug, make more than one solute/particulate, then delete an object that is not on the bottom, then add a new object. The new objectFrame
will be drawn over the bottom object. you can verify this by pressing 'delete' on the bottom object, which reveals the covered one.
'''

class BiofilmApp(customtkinter.CTk):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.set_up_window()
        self.params = self.initialize_parameters()
        self.particulates_arr = []
        self.solutes_arr = []
        #self.reactionSF = None

        self.create_menu()
        self.appFrame.pack()
        self.create_parameter_frame()
        self.create_frames()
        self.bind_events()
        self.mainloop()


    def set_up_window(self):
        customtkinter.set_appearance_mode("System")
        customtkinter.set_default_color_theme("blue")
        self.title("Biofilm.py")
        self.height = self.winfo_screenheight()
        self.width = self.winfo_screenwidth()
        self.appFrame = customtkinter.CTkFrame(master = self, width=self.width, height=self.height)
        self.appFrame.pack_propagate(0)
        self.geometry("%dx%d+0+0" % (self.width, self.height - 100))
        self.update()


    def initialize_parameters(self):
        #dictionary of parameters, each value is a stringvalue, which is a wrapper around a string which can be put in an entry box widget, and the variable automatically updates the value.
        #enter default values of variables here
        params = {
            "title": customtkinter.StringVar(value=""),
            "run_time": customtkinter.StringVar(value="1"),
            "tolerance": customtkinter.StringVar(value="1e-4"),
            "output_period": customtkinter.StringVar(value="0.1"),
            "kdet": customtkinter.StringVar(value="100"),
            "volume": customtkinter.StringVar(value="0"),
            "surface_area": customtkinter.StringVar(value="0"),
            "flowrate": customtkinter.StringVar(value="0"),
            "gridpoints": customtkinter.StringVar(value="10"),
            "initial_thickness": customtkinter.StringVar(value="0.1"),
            "layer_thickness": customtkinter.StringVar(value="0.1"),
            "yield_coefficients": np.empty(0), #will hold an np array where rows represent particulates, columns represent solutes. data type is float.
            "file_path": ""     #Note, because file_path will never be used with an entryBox, it is just a string
        }
        self.plot_window = None
        return params


    def do_nothing(self):
        pass


    def create_menu(self):
        #Create menu bar - File Edit ect.
        menubar = CTkMenuBar.CTkMenuBar(self)
        file_button = menubar.add_cascade("file")
        filemenu = CTkMenuBar.CustomDropdownMenu(widget = file_button)
        filemenu.add_option(option="Open", command=self.load)
        filemenu.add_option(option="Save", command=self.save)
        filemenu.add_option(option="Save as...", command=self.save_as)
        menu_frame = customtkinter.CTkFrame(self.appFrame, width=self.winfo_screenwidth() / 5, height=self.winfo_screenheight() - 40)
        menu_frame.grid(row=0, column=0, pady=5, ipady=40, padx=5, sticky="N")
        menu_frame.grid_propagate(0)

        sim_button = customtkinter.CTkButton(menu_frame, text="Simulation Parameters", width=(self.winfo_screenwidth() / 5) - 20, command=self.simulation_button_func)
        sim_button.grid(row=1, column=0, pady=5, padx=10)
        geometry_button = customtkinter.CTkButton(menu_frame, text="Geometry Parameters", width=(self.winfo_screenwidth() / 5) - 20, command=self.geometry_button_func)
        geometry_button.grid(row=2, column=0, pady=5, padx=10)
        particulate_button = customtkinter.CTkButton(menu_frame, text="Particulate Parameters", width=(self.winfo_screenwidth() / 5) - 20, command=self.particulate_button_func)
        particulate_button.grid(row=3, column=0, pady=5, padx=10)
        solute_button = customtkinter.CTkButton(menu_frame, text="Solute Parameters", width=(self.winfo_screenwidth() / 5) - 20, command=self.solute_button_func)
        solute_button.grid(row=4, column=0, pady=5, padx=10)
        reaction_button = customtkinter.CTkButton(menu_frame, text="Reactions", width=(self.winfo_screenwidth() / 5) - 20, command=self.reaction_button_func)
        reaction_button.grid(row=5, column=0, pady=5, padx=10)
        customtkinter.CTkButton(menu_frame, text="Run Simulation", width=(self.winfo_screenwidth() / 5) - 20, command=self.run_handler).grid(row=6, column=0, pady=50, padx=10, sticky="s")
        customtkinter.CTkButton(menu_frame, text="Test", width=(self.winfo_screenwidth() / 5) - 20, command=self.open_plot_window).grid(row=7, column=0, pady=50, padx=10, sticky="s")
        self.menu_buttons = [sim_button, geometry_button, particulate_button, solute_button, reaction_button]


    def create_parameter_frame(self):
        self.parameter_frame = customtkinter.CTkFrame(self.appFrame, height=self.winfo_screenheight(), width=(4 * self.winfo_screenwidth() / 5) - 26)
        self.parameter_frame.grid(row=0, column=1, pady=5, padx=5, sticky="N")
        self.parameter_frame.grid_propagate(0)


    def create_frames(self):
        self.init_simulation_frame()
        self.init_geometry_frame()
        self.particulate_frame = customtkinter.CTkFrame(self.parameter_frame, height=self.winfo_screenheight(), width=(4 * self.winfo_screenwidth() / 5) - 60)
        self.init_particulate_frame()
        self.solute_frame = customtkinter.CTkFrame(self.parameter_frame, height=self.winfo_screenheight(), width=(4 * self.winfo_screenwidth() / 5) - 60)
        self.init_solute_frame()
        self.reaction_frame = customtkinter.CTkFrame(self.parameter_frame, height=self.winfo_screenheight(), width=(4 * self.winfo_screenwidth() / 5) - 60)
        

    def save_as(self):
        kinetics = self.reactionSF.getKinetics()
        SFB = SaveFileBuilder.SaveFileBuilder(self.params, self.particulates_arr, self.solutes_arr, kinetics)
        content = SFB.makeSaveFileContent()
        fc = FileController.FileController()
        file_path = fc.saveAs(content)
        self.params['file_path'] = file_path


    def save(self):
        if self.params['file_path'] == '':
            self.save_as()
            return
        kinetics = self.reactionSF.getKinetics()
        SFB = SaveFileBuilder.SaveFileBuilder(self.params, self.particulates_arr, self.solutes_arr, kinetics)
        content = SFB.makeSaveFileContent()
        fc = FileController.FileController()
        fc.save(content, self.params['file_path'])


    def load(self):
        fc = FileController.FileController()
        #invoke load function on fileController, this uses filedialog to open the window where the user selects file to load
        #this function returns the file path of the selected load file and a string 'file_contents' which is the whole file in one sring
        file_path, file_contents = fc.load()
        if file_path != 0:
            #update 'file_path' pointer in params
            self.params['file_path'] = file_path

            #make new FileLoader object, passing in file contents string. 
            fl = FileLoader.FileLoader(file_contents)
            #This function loads the file's params into self.params, and makes the solute/partuculate objects and the yxs matrix
            solutes, particulates, yxs = fl.saveDataToStructures(self.params, self.SoluteSOF, self.ParticulateSOF)
            self.solutes_arr = solutes
            self.SoluteSOF.loadFrames(solutes)
            self.particulates_arr = particulates
            self.ParticulateSOF.loadFrames(particulates)
            self.params["yield_coefficients"] = yxs


    def clearParameterFrame(self):
        self.simulation_frame.grid_forget()
        self.geometry_frame.grid_forget()
        self.particulate_frame.grid_forget()
        self.solute_frame.grid_forget()
        self.reaction_frame.grid_forget()
    

    def bind_events(self):
        #self.bind('<Destroy>', self.quitting)
        pass


    #Initializing different side menu options:
    def init_simulation_frame(self):
        self.simulation_frame = SimulationFrame.SimulationFrame(params=self.params, parent=self.parameter_frame, height=self.winfo_screenheight(), width=(4 * self.winfo_screenwidth() / 5) - 60)


    def init_geometry_frame(self):
        self.geometry_frame = GeometryFrame.GeometryFrame(params=self.params, parent=self.parameter_frame, height=self.winfo_screenheight(), width=(4 * self.winfo_screenwidth() / 5) - 60)


    def init_particulate_frame(self):
        self.ParticulateSOF = ScrollableObjectFrame.ScrollableObjectFrame(self.params, self.particulate_frame, self.particulates_arr, False, height = self.winfo_screenheight()-20, width = ((4*self.winfo_screenwidth())/5)-50)
        self.ParticulateSOF.grid(row = 0, column = 0)


    def init_solute_frame(self):
        self.SoluteSOF = ScrollableObjectFrame.ScrollableObjectFrame(self.params, self.solute_frame, self.solutes_arr, True, height = self.winfo_screenheight()-20, width = ((4*self.winfo_screenwidth())/5)-50)
        self.SoluteSOF.grid(row = 0, column = 0)
    

    def init_reaction_frame(self):
        self.reactionSF = ReactionFrame.ReactionFrame(self.reaction_frame, self.params, self.solutes_arr, self.particulates_arr,height = self.winfo_screenheight()-20, width = ((4*self.winfo_screenwidth())/5)-50) #ReactionSF = reactionScrollableFrame
        self.reactionSF.grid(row = 0, column = 0)


    #Functions for side menu buttons:
    def enableAllButtons(self):
        for button in self.menu_buttons:
            button.configure(state="normal")


    def disableButton(self, button_index): #disable a menu button of a given index, indices are defined here: [sim_button, geometry_button, particulate_button, solute_button, reaction_button]
        self.menu_buttons[button_index].configure(state = "disabled")


    def menuButtonPress(self, button_index):
        self.clearParameterFrame()
        self.enableAllButtons()
        self.disableButton(button_index)
    

    def simulation_button_func(self):
        self.menuButtonPress(button_index=0)
        self.simulation_frame.grid(row = 0, column = 0, pady = 5, padx = 5, ipadx = 5, ipady = 3) 


    def geometry_button_func(self):
        self.menuButtonPress(button_index=1)
        self.geometry_frame.grid(row = 0, column = 0, pady = 5, padx = 5, ipadx = 5, ipady = 3) 


    def particulate_button_func(self):
        self.menuButtonPress(button_index=2)
        self.particulate_frame.grid(row = 0, column = 0, pady = 5, padx = 5, ipadx = 5, ipady = 3)


    def solute_button_func(self):
        self.menuButtonPress(button_index=3)
        self.solute_frame.grid(row = 0, column = 0, pady = 5, padx = 5, ipadx = 5, ipady = 3) 


    def reaction_button_func(self):
        self.menuButtonPress(button_index=4)
        self.init_reaction_frame()
        self.reaction_frame.grid(row = 0, column = 0, pady = 5, padx = 5, ipadx = 5, ipady = 3)
        self.reactionSF.update() 


    def run_handler(self): #called when 'run simulation' is pressed
        return_val, content = self.run_julia_script()
        #return_val == 1 if no error running the file
        if return_val == 1:
            self.open_plot_window()

    def open_plot_window(self):
        if self.plot_window is None or not self.plot_window.winfo_exists():
            step = float(self.params.get('output_period').get())
            tfinal = float(self.params.get('run_time').get())
            self.plot_window = PlotWindow.PlotWindow(master = self, tfinal = tfinal, step = step)  # create window if its None or destroyed
            self.plot_window.focus()
        else:
            self.plot_window.focus()  # if window exists focus it
        self.plot_window.lift()
        self.plot_window.attributes('-topmost', True)
        self.plot_window.after(200, lambda: self.plot_window.attributes('-topmost', False))


    def run_julia_script(self):
        # Function to run Julia script
        print("RUNNING SCRIPT")
        try:
            # Run the Julia script as a subprocess and capture its output
            completed_process = subprocess.run(['julia', self.params["file_path"]], check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
            
            # Access the output and error streams
            output = completed_process.stdout
            error = completed_process.stderr

            # Handle the output as needed
            if output:
                print("Output:", output)
            if error:
                print("Error:", error)
            return 1, output
        except subprocess.CalledProcessError as e:
            print(f"Error running Julia script: {e}")
            return 0, 0
       

    def quitting(self, event):
        print('quitting')
        customtkinter.CTk.quit(self)

#if __name__ == "__main__":
#    app = BiofilmApp()
#    app.mainloop()

app = BiofilmApp()
app.mainloop()